### ISSUE TITLE
Show the "Secret is not strong" error under Account secret field

### ISSUE THREAD

**Issue by muralidharan1001** [maidsafe/safe-authenticator-mobile#101]
In create account page,
- `Secret is not strong` error need to be shown under the secret field, currently it is shown under confirm secret field (in second carousel page).
- The same has to be implemented in the password field also (in third carousel page).

**Comment by safesurfer** [comment]
Tested it, `secret strength` error msg coming under first secret field, and `fields doesn't match` error coming under confirm secret field. It's possible to see both the error messages at once. Is it right @muralidharan1001 ? Aren't we checking the strength first and only if it is true then we check field match? I'm not sure abt it, but wanted to confirm

![screenshot_2019-02-28-18-19-23-960_net maidsafe safeauthenticator](https://user-images.githubusercontent.com/27578024/53567664-edee0900-3b85-11e9-947b-001ed3d58e89.jpg)

**Comment by muralidharan1001** [comment]
> Aren't we checking the strength first and only if it is true then we check field match?

we have that as a separate issue #94, it has more complications. This error text senario will be sorted out along with that.

**Comment by safesurfer** [comment]
OK, I'm moving this to done
