### ISSUE TITLE
When requesting authorization for Messages app on android

### ISSUE THREAD

**Issue by bochaco** [maidsafe/safe-authenticator-mobile#12]
Issue moved from https://github.com/maidsafe/beaker-plugin-safe-authenticator/issues/148 to here for analysis/validation.

Error code : -11. Description : code error : routing interface error -> EventSenderError(EventSubset("SendError(...)"))

**Comment by ashwinkumar6** [comment]
@gso6 thanks for reporting the issue. Can you try building the safe-authenticator from [here](https://github.com/maidsafe/safe-authenticator-mobile)

**Comment by ravinderjangra** [comment]
closing inactive issue.
