### ISSUE TITLE
 Hide auto-reconnect option if API level < 19

### ISSUE THREAD

**Issue by ashwinkumar6** [maidsafe/safe-authenticator-mobile#122]
The auto-reconnect option present in the `SettingPage`, when turned on is used to store the user's credentials in a secure store on `KeyStore` and `KeyChain` for Android and iOS respectively. The library user for this is [Xamarin.Essentials](https://docs.microsoft.com/en-us/xamarin/essentials/secure-storage?context=xamarin%2Fios&tabs=android). This feature is not supported in Android when the API level <19. 
Hence hide the auto-reconnect feature on Android when the API level < 19

**Comment by S-Coyle** [comment]
Verified fixed
