### ISSUE TITLE
Authenticator not supported on armeabi-v7a, API level 16

### ISSUE THREAD

**Issue by ashwinkumar6** [maidsafe/safe-authenticator-mobile#125]
There is an [existing issue](https://github.com/xamarin/xamarin-android/issues/2392) on Xamarin.Forms regarding this. The issue seems to be with the mono runtime. This issue can also be reproduced by creating a new Xamarin.Forms app and running it on a device with architecture `armeabi-v7a` and with API level 16

**Comment by ravinderjangra** [comment]
the minimum supported platform is API 20
