### ISSUE TITLE
Authenticator crashes if registered URI is not found when redirecting to other apps

### ISSUE THREAD

**Issue by ashwinkumar6** [maidsafe/safe-authenticator-mobile#126]
After authorizing a request from an application on the authenticator, the response is sent back to the app. The user is redirected to the app using it's [registered URI](https://xamarinhelp.com/uri-scheme/). If the registered URI is not found the authenticator crashes.

A solution to this would be to use a [native control](https://xamarinhelp.com/launching-mobile-app-via-uri-scheme/) to check if the app is present on the device using its registered URI. If it is present redirect to the app if not display an error state on the authorization popup with the message "An app with the ID <AppId> was not found"

**Comment by safesurfer** [comment]
QA verified
