### ISSUE TITLE
Wrong container name displayed for app containers of other apps

### ISSUE THREAD

**Issue by lionel1704** [maidsafe/safe-authenticator-mobile#127]
Consider two applications A and B. 
If application A sends a container request that requests access to app B's container (`apps/app.b.id`) the authenticator application displays the container name as "App's own container" which is incorrect.

**Comment by ashwinkumar6** [comment]
There are three scenarios to be handled here
1) App A requests for its own container :
Display container name is `Apps own container`

2) App A requests for App B's container, App B is currently registered :
Display container name is `<App name> container`

3) App A requests for App B's container, App B is currently revoked :
Display container name is `Application <AppID> container`

**Comment by lionel1704** [comment]
In scenario 3 - why would we want to display the app ID to the user? Isn't that bad UX?

**Comment by ashwinkumar6** [comment]
Actually for scenario 3, when the app is revoked it's not present in the `RegisteredAppList` and so a call is to be made to the network to fetch the list of revoked apps using which we can determine the app name from the ID. 
This will take much more time to process the request when compared to the other two scenarios.

**Comment by lionel1704** [comment]
Well there might still be a good way to handle this..... For example, if you have _only_ the app ID then you can display the App ID temporarily while the application fetches the list of revoked apps in the background. Once this list is fetched you can replace the app ID with the application name.

**Comment by ashwinkumar6** [comment]
In that case, I think it's important to display some sort of a loading state during the background process. So the order would be
1) Display appId with a loading state
2) Fetch the revoked apps in the background
3) Replace fetched app name with appId and remove loading state

**Comment by safesurfer** [comment]
The container name is truncated at the end, ie., if I use `apps/hello`, the error messages shows `hell` by truncating the last letter `o`.
![image](https://user-images.githubusercontent.com/27578024/57610292-264e9200-758e-11e9-9a2c-558a4270d367.png)

**Comment by ravinderjangra** [comment]
@safesurfer This issue is fixed in #144. Please verify the same.

**Comment by safesurfer** [comment]
QA verified.
