### ISSUE TITLE
Application does not handle incorrect container names

### ISSUE THREAD

**Issue by lionel1704** [maidsafe/safe-authenticator-mobile#128]
When sending an authentication request / container request with an invalid container name, the authenticator mobile application crashes. This cannot be handled at the native layer as the native libraries perform only encoding and decoding. The application can handle these invalid container names instead of the current behaviour - app crash

**Comment by ashwinkumar6** [comment]
After receiving the encoded request from a SAFE app, decode the request and perform a check if all the requested containers are valid. If any container is invalid then don't display the authorization popup dialog instead display an error indicating that the particular container is invalid

**Comment by safesurfer** [comment]
Tested this scenario @ashwinkumar6 , but the container name in the error message is truncated at the beginning. i.e, if the container name is `abcd` the error messsage shows it as `Bcd`.

**Comment by ashwinkumar6** [comment]
[PR #141](https://github.com/maidsafe/safe-authenticator-mobile/pull/141) has been raised to this.

**Comment by safesurfer** [comment]
QA verified
