### ISSUE TITLE
Add additional constants, refactor convertors 

### ISSUE THREAD

**Issue by ashwinkumar6** [maidsafe/safe-authenticator-mobile#134]
- Currently, some converters are redundant, Replace `ContainerNameToImageConverter` and `FormatContainerNameConverter` with necessary converters directly in the code behind if required 
- Add constants for 
  - `ErrorCode`
  - `ErrorCodeMessage` 
  - `StringStrength` 
  - `StringStrengthScore`

**Comment by safesurfer** [comment]
QA reviewed
