### ISSUE TITLE
Resume app revocation process after Authenticator reconnect

### ISSUE THREAD

**Issue by ravinderjangra** [maidsafe/safe-authenticator-mobile#139]
In the current implementation, if we close the app immediately after the revoking process started, this may result in misinformation as the app is still available in the app revocation list (network side) and the revocation process needs to be continued after the Authenticator client is reconnected to the network.

We need to have a check in place (using some bool property) so that on reconnect we can call the `flush_app_revocation_queue` API. This will solve the problem assuming that the device is being used by one user.

In future, we can add an API like `is_app_revocation_queue_empty` in SCL side and use that to check if any revocation if still pending (will help us to use the API across all platforms & devices).

**Comment by safesurfer** [comment]
QA verified
