### ISSUE TITLE
Not able to authorise apps on Android Pie 9.0

### ISSUE THREAD

**Issue by safesurfer** [maidsafe/safe-authenticator-mobile#142]
Tried authorising apps from mobile which is having version 9.0 (Android Pie), is not allowing me to authorise. It throws the following error.
Tested on lower versions like Oreo, Nouget, etc. It works fine on them.

![Screenshot_20190510-141551](https://user-images.githubusercontent.com/27578024/57514840-f05fa280-732e-11e9-87c9-ee09b81eae55.png)

**Comment by ravinderjangra** [comment]
Could you please add the error log?

**Comment by safesurfer** [comment]
I've updated my comment, @ravinderjangra !

**Comment by ashwinkumar6** [comment]
[PR #141](https://github.com/maidsafe/safe-authenticator-mobile/pull/141) has been raised to resolve this.

**Comment by safesurfer** [comment]
QA verified
