### ISSUE TITLE
"Choose a Vault" page improvement

### ISSUE THREAD

**Issue by ravinderjangra** [maidsafe/safe-authenticator-mobile#208]
Potential improvements for searching for config files on device.

- `Downloads` or `Download`? https://safenetforum.org/t/new-release-safe-authenticator-v0-2-0-safe-mobile-browser-v0-3-0/31092/27?u=stephenc
- Add a filter to only show `.conf` files? https://safenetforum.org/t/new-release-safe-authenticator-v0-2-0-safe-mobile-browser-v0-3-0/31092/29?u=stephenc

**Comment by ravinderjangra** [comment]
I was previously looked into this @S-Coyle .

- **Downloads/Download:** It totally depends on the user device. The file is always stored where used downloaded using their browser which is similar to downloading and saving any other file.
- **.config file:** It doesn't seem possible with .config file cause I couldn't find any particular MIMEType for this file extension using which I can add a filter. Had some discussion here on the slack: https://maidsafe.slack.com/archives/C09T536UF/p1581666328244600

**Comment by S-Coyle** [comment]
@ravinderjangra 
* **Download/Downloads**: Sounds like nothing we can help with.
* **.config file**: and the linked slack discussion - also unfortunately no way to help filter then, though there would be a way if we changed from .config to something like .json.

This logged issue is no longer relevant. Closing and have logged #210 to track the switch from .config to .json.
