### ISSUE TITLE
"Choose a Vault" page design feedback.

### ISSUE THREAD

**Issue by ravinderjangra** [maidsafe/safe-authenticator-mobile#209]
See https://safenetforum.org/t/new-release-safe-authenticator-v0-2-0-safe-mobile-browser-v0-3-0/31092/23?u=stephenc (and other opinion(s) further below)

**Comment by ravinderjangra** [comment]
Hey @S-Coyle, do you think we need any more changes on the vault page? If not then we can close this one.

**Comment by S-Coyle** [comment]
I believe we're good now, closing
