### ISSUE TITLE
Android v6.0 - unable to login/connect to shared section

### ISSUE THREAD

**Issue by S-Coyle** [maidsafe/safe-authenticator-mobile#220]
Thank you for contributing to the project!
We recommend you check out our ["Contributing to the SAFE Network"](https://github.com/maidsafe/QA/blob/master/CONTRIBUTING.md) guide if you haven't already.

**Describe the bug**
Unable to login/connect to the shared section on an Android v6 emulator

**To Reproduce**
Steps to reproduce the behavior, e.g.:
1. Install latest authenticator app on v6.0 emulator
2. Click to download the shared section config file
3. Attempt ro log on with valid details
4. See error "Could not connect to the SAFE Network

**Expected behavior**
On latest versions of Android this connects without any issues

**Smartphone (please complete the following information where applicable):**
 - Device: Google Pixel 3 Emulator
 - OS: Android v6
 - safe-authenticator-mobile version: [e.g. 0.3.0]

**Additional context**
Tested using browser on same emulator & it also fails - see issue logged [here](https://github.com/maidsafe/safe-mobile-browser/issues/258)

**Comment by ravinderjangra** [comment]
Duplicate: https://github.com/maidsafe/safe-authenticator-mobile/issues/195
