### ISSUE TITLE
Initial white screen on loading

### ISSUE THREAD

**Issue by safesurfer** [maidsafe/safe-authenticator-mobile#31]
While loading authenticator, it shows a white screen for a few seconds. @shankar2105 is suggesting that we can have a splash screen.

**Comment by ashwinkumar6** [comment]
Add the authenticator logo in the centre with a white background as the splash screen in android and iOS.
Generate different sizes of logo image and add them to the resources directory to handle splash screen for all devices sizes

**Comment by safesurfer** [comment]
QA verified
