### ISSUE TITLE
Add linter to enforce coding standards 

### ISSUE THREAD

**Issue by ashwinkumar6** [maidsafe/safe-authenticator-mobile#32]
- Add StyleCop.Analyzers nuget package
- Update existing code to follow stylecop (all projects)
- CI builds are expected to fail if stylecop checks do not pass. Results of failures should be visible in the CI console tab

**Comment by ashwinkumar6** [comment]
fixed here [PR](https://github.com/maidsafe/safe-authenticator-mobile/issues/32)

**Comment by safesurfer** [comment]
Tested linter by stylistic errors like adding extra space before parenthesis, removing indent for curly braces, removing eol, no proper indentation etc., locally and in CI as well and CI failed as expected.
