### ISSUE TITLE
User allows an Empty container request access - Display the message "no container permissions were requested"

### ISSUE THREAD

**Issue by vinitha-vasanthkumar** [maidsafe/safe-authenticator-mobile#39]
When app sends an container permission request to the authenticator and user allows the request. The authenticator app details screen displays the Container permissions heading with no message. Display the message "no container permissions were requested"

**Comment by ravinderjangra** [comment]
@S-Coyle, @vinitha-vasanthkumar  please check the updated screen. If this is okay then I can raise a PR.

![screenshot_1544699514](https://user-images.githubusercontent.com/9795917/49935077-0d19ba80-fef6-11e8-860c-802276c62ed2.png)

**Comment by S-Coyle** [comment]
That fix would be fine for me @ravinderjangra
