### ISSUE TITLE
Update packages to support Android 9.1 and iOS 12.1

### ISSUE THREAD

**Issue by ashwinkumar6** [maidsafe/safe-authenticator-mobile#4]
- Update all packages in SafeAuthenticator to support the latest versions of Android and IOS
- Updating to the latest versions would help us improve performace and memory usage, use the latest featues of xamarin.forms and make the app compatible with devices running the latest versions of android and iOS

**Comment by safesurfer** [comment]
Tested it on mac mini using simulator. though it was slow, it was working well. tested it with auth request tool app.
