### ISSUE TITLE
Login to Handle Unregistered Request

### ISSUE THREAD

**Issue by ashwinkumar6** [maidsafe/safe-authenticator-mobile#48]
- In the current implementation, the user is required to be logged in to allow/deny and unregistered request, the user should be able to handle this without logging in as well 
- Currently an unregistered request sent to the authenticator requires to be in the format 
`safe-auth://<appID>/<encodedString>/unregistered` , update such that `safe-auth://<appID>/<encodedString>` format is supported 

solution:  In HandleUrlActivation() function present in AuthService class if the encoded request is of type `UnregisteredIpcReq` then display a popup requesting the user to authenticate the app. Handle this scenario before logging in as well as after logging in

**Comment by safesurfer** [comment]
QA Verified
