### ISSUE TITLE
Delay in back button title change when navigate from feature screens in iOS

### ISSUE THREAD

**Issue by muralidharan1001** [maidsafe/safe-authenticator-mobile#59]
In iOS, while navigating from the feature screen (TutorialPage) to the CreateAcctPage. The back button on the top left should say "Login" in place of "Back" but there is a delay in replacing this text.
A simple solution would be to remove the text, but it is prefered to display the login text seamlessly.

**Comment by ashwinkumar6** [comment]
Instead of removing the back button title on `CreateAcctPage`, a quick fix would be to set the `BackButtonTitle` property as `Login` in `TutorialPage`, this will prevent the back button's title from changing when navigating from feature screens in iOS
