### ISSUE TITLE
FAQ link is not working under Settings

### ISSUE THREAD

**Issue by safesurfer** [maidsafe/safe-authenticator-mobile#61]
FAQ link is not working in Settings when we click it.

STR:
1. Open authenticator and Login
2. Click Settings (gear) icon on the top right of the screen
3. Click FAQ in Settings page, which is not redirecting to the FAQ doc.

**Comment by ashwinkumar6** [comment]
The TapGestureRecognizer command binding set for the FAQ link in `SettingsPage` is not valid, to fix this rename `FAQCommand` to `FaqCommand` in `SettingsPage`.
