### ISSUE TITLE
Login page title is shown for fraction of a second and disappears

### ISSUE THREAD

**Issue by safesurfer** [maidsafe/safe-authenticator-mobile#62]
Login page title is shown for fraction of a second and disappears, when we click back button from `Create Account` page

STR:
1. Open authenticator and click `Create Account`
2. Create account page will be shown, now click back button
3. while redirecting to Login page, for a fraction of a second, Login page title will be shown.

**Comment by ashwinkumar6** [comment]
The `HasNavigationBar` property of LoginPage has been disabled but the `Title` property is set, so the title appears for a fraction of second and then disappears. A quick fix would be to remove the `Title` property
