### ISSUE TITLE
Double tapping applications in Registered app list, opens two app info pages

### ISSUE THREAD

**Issue by safesurfer** [maidsafe/safe-authenticator-mobile#65]
Double tapping a single application or quickly tapping two other applications from the Registered app list, open two app info pages of the single or two other applications respectively.

STR:
1. Open authenticator and Login
2. Registered apps are listed in the home page
3. Double tap a single app or quickly tap two other apps
4. it opens two app info pages, and if we want to access the reg app page, we need to tap back button twice.

![issue](https://user-images.githubusercontent.com/27578024/52413009-58230900-2b06-11e9-95cf-ad4dfc780709.gif)

**Comment by ashwinkumar6** [comment]
This is the default behavior for a lot of apps in android, Eg Swiggy, Facebook, Zomato, Whatsapp. 
The items can be clicked more than once and the respective pages are also opened more than once.

**Comment by safesurfer** [comment]
Closing this issue since it is a default behavior for many apps in androids like @ashwinkumar6 commented.
