### ISSUE TITLE
Font size looks small in ios

### ISSUE THREAD

**Issue by safesurfer** [maidsafe/safe-authenticator-mobile#67]
Font size looks small in ios authenticator

**Comment by ravinderjangra** [comment]
on which page/control @safesurfer?

**Comment by safesurfer** [comment]
all over the application, (app list, settings page) font size looks small compare to other ios pages, for ex: I compared it with Settings page of ios. @ravinderjangra ,

**Comment by muralidharan1001** [comment]
The text font size needs to be increased in all pages for iOS.
