### ISSUE TITLE
No animation for clickable items in Settings page

### ISSUE THREAD

**Issue by safesurfer** [maidsafe/safe-authenticator-mobile#68]
No animation for clickable items like FAQ, Privacy under Settings. 
It's on both ios and android

**Comment by ashwinkumar6** [comment]
The FAQ, Privacy links under SettingsPage will not have a tap animation since these are labels. To add a tap animation to these add these two labels as items of a listview

**Comment by ashwinkumar6** [comment]
A listview is not required, the above can also be achieved by using the [XamEffects](https://github.com/mrxten/XamEffects) for adding effects.
