### ISSUE TITLE
`Need any help?` text is cropped in Login page in ios

### ISSUE THREAD

**Issue by safesurfer** [maidsafe/safe-authenticator-mobile#69]
`Need any help?` text is cropped at the bottom in Login page in ios device.

**Comment by ravinderjangra** [comment]
Is it cropped or overlapped by keyboard?

**Comment by ravinderjangra** [comment]
It has been already reported in #60. Or would you like to track both separately?

**Comment by safesurfer** [comment]
@ravinderjangra , it is cropped, though the keyboard is not invoked. I meant to say that the letters `y` and `p` in the text `Need any help?` are cropped at the bottom in the first screen itself. it's only on ios, not in android. so it is not related to #60 also

**Comment by ashwinkumar6** [comment]
Adjust the `VerticalOptions` and `Height` property of the `Need any help` label in LoginPage to prevent the text from getting cropped
