### ISSUE TITLE
Fix auto-reconnect issue while application resumes from background.

### ISSUE THREAD

**Issue by ashwinkumar6** [maidsafe/safe-authenticator-mobile#8]
When SafeAuth remains in the background for really long auto-reconenct doesn't work at times, cache is not cleared when user logsout of app

AutoReconnect option (switch) is used to automatically connect to the network once the user has logged in if it is toggled on, 
- User credentials are to be cached as long as the app remains in the background
- Cache needs to be cleared when user logsout of SafeAuthenticator

**Comment by ravinderjangra** [comment]
Fixed by #19
