### ISSUE TITLE
No padding between `Invitation token` label and the text field in Create Account page

### ISSUE THREAD

**Issue by safesurfer** [maidsafe/safe-authenticator-mobile#84]
The blinking text cursor (I-beam pointer) in the text field slightly overlaps with the label text `Invitation token` in the Create Account page.

**Comment by safesurfer** [comment]
![invite](https://user-images.githubusercontent.com/27578024/53000379-37d04400-344e-11e9-9998-47f2b200c599.jpg)

**Comment by muralidharan1001** [comment]
Increase the padding value in the `Control.EditText.SetPadding()` in material renderer
