### ISSUE TITLE
Check the strength of Secret/Password before matching with confirm fields

### ISSUE THREAD

**Issue by muralidharan1001** [maidsafe/safe-authenticator-mobile#94]
In CreateAcctPage there are two checks
- The strength of secret and password
- The matching of the secret/password field and the confirm secret/password field

Current implementation order:
1. Check the field matching
2. Check the strength

The strength of secret/password cannot be checked while typing is related to the issue #35 

To have a better user experience the order should be changed:
1. Check the strength while typing the secret/password after this is done.
2. Then allow the user to enter the confirm secret/password field and check whether it is matching.

**Comment by ravinderjangra** [comment]
Closing this. This will be implemented in SNAPP.
